// header for flash file system data generated by mkffs
typedef struct { 
    char *path; 
    char *mime; 
    char *enc; 
    unsigned int off; 
} ffsinfo;

typedef struct {
    unsigned int idx;
    unsigned int rem;
} ffsending;

#define INFLASH __attribute__((section(".irom0.text")))
