#!/usr/bin/env python
#
#   Make a C data string for a given file, gzipped
#   
#   Usage: mkdata <infile> <outfile> <var name>
#
import sys, zlib, gzip

with open(sys.argv[1], "rb") as f: 
    fileBytes = f.read()
    gzip_compress = zlib.compressobj(9, zlib.DEFLATED, zlib.MAX_WBITS | 16)
    gzipdata = gzip_compress.compress(fileBytes) + gzip_compress.flush()
    
fileHex = ', '.join(hex(x) for x in bytearray(gzipdata))
fileLen = len(gzipdata)

with open(sys.argv[2], "wb") as f:
    f.write('#include "c_types.h"\n#include "user_config.h"\n\nconst unsigned int %s_len = %d;\nconst INFLASH uint8_t %s[]={%s};' 
        % (sys.argv[3], fileLen, sys.argv[3], fileHex))
